### ISSUE TITLE
Mod or script ?

### ISSUE THREAD

**Issue by ImplicitDeny** [team-gsri/GOS#1]
@ArwynFr should the GOS be shipped as a mod or as a script ?
I tends to think about it the same way I think about GZM or Opex now : as a mod, we can mass update missions more easily. The drawback being that we need a modpack update before fixing issues.

Any thoughts ?

**Comment by ArwynFr** [comment]
It can be made as a mod to decrease the work needed to create a mission with it.

However, the mod shall do nothing unless explicitly activated in the mission by an editor knowing that mod existence (via mission CBA setting for instance). Otherwise, this mod may break mission developed by author unaware of it.

**Comment by ArwynFr** [comment]
@ImplicitDeny can we close this with agreement ?

**Comment by ImplicitDeny** [comment]
Yes we can !
